worker_processes auto;
events { worker_connections 2048; }

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;

  upstream auth_upstream {
    server auth-service:3001;
  }
  upstream clinical_upstream {
    server clinical-service:3002;
  }
  upstream ia_upstream {
    server ia-service:3003;
  }

  server {
    listen 80;
    server_name _;

    # Entrada unica para cada uno de los servicios
    location /api/auth/ {
      proxy_pass http://auth_upstream/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Authorization $http_authorization;
    }

    location /api/clinical/ {
      proxy_pass http://clinical_upstream/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Authorization $http_authorization;
    }

    location /api/ia/ {
      proxy_pass http://ia_upstream/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}